"use strict";

// Sources: W1–W3 = lecture PDFs; A1–A3 = the three local assignments.
const QUIZ_TOPICS = [
  {id:"web",en:"Web basics",kk:"Веб негіздері"},
  {id:"html",en:"HTML structure",kk:"HTML құрылымы"},
  {id:"content",en:"Text, links & images",kk:"Мәтін, сілтеме және сурет"},
  {id:"tables",en:"Lists & tables",kk:"Тізімдер мен кестелер"},
  {id:"forms",en:"Forms & attributes",kk:"Формалар мен атрибуттар"},
  {id:"selectors",en:"CSS & selectors",kk:"CSS және селекторлар"},
  {id:"style",en:"Text, color & box model",kk:"Мәтін, түс және box model"},
  {id:"effects",en:"Position & effects",kk:"Орналасу және әсерлер"},
  {id:"flex",en:"Flexbox",kk:"Flexbox"},
  {id:"grid",en:"CSS Grid",kk:"CSS Grid"},
  {id:"responsive",en:"Responsive & Bootstrap",kk:"Адаптивтік дизайн және Bootstrap"}
];

const QUIZ_QUESTIONS = [];
function Q(topic,source,en,kk,choices,answer,whyEn,whyKk){
  QUIZ_QUESTIONS.push({id:QUIZ_QUESTIONS.length+1,topic,source,en,kk,
    choices:choices.map(value=>{const [en,kk]=value.split("|");return {en,kk};}),answer,whyEn,whyKk});
}

// WEEK 1 — Internet, HTML, and the elements used in Assignment 1.
Q("web","W1","What is the Internet?","Интернет деген не?",["A global network of connected computers|Бір-біріне қосылған компьютерлердің әлемдік желісі","A single HTML page|Бір HTML беті","A CSS file|CSS файлы","A browser tab|Браузер қойындысы"],0,"The Internet is the network; the Web is one service that uses it.","Интернет — желі, ал веб — сол желіні пайдаланатын қызметтің бірі.");
Q("web","W1","What is the World Wide Web (WWW)?","World Wide Web (WWW) деген не?",["The physical computer network|Компьютерлердің физикалық желісі","A collection of web pages and sites accessed through the Internet|Интернет арқылы ашылатын веб беттер мен сайттар жиынтығы","Only the browser program|Тек браузер бағдарламасы","A type of CSS selector|CSS селекторының түрі"],1,"The Web consists of linked pages and sites delivered over the Internet.","Веб — интернет арқылы жеткізілетін өзара байланысқан беттер мен сайттар.");
Q("web","W1","In the client–server model, what is usually the client?","Клиент–сервер жүйесінде әдетте клиент не болады?",["A browser requesting a page|Бетті сұрайтын браузер","The CSS stylesheet|CSS стиль файлы","An image element|Сурет элементі","The page footer|Беттің төменгі бөлігі"],0,"The browser sends a request; the server sends a response.","Браузер сұрау жібереді, сервер жауап қайтарады.");
Q("web","W1","Which technology gives a webpage its structure?","Веб бетке құрылым беретін технология қайсы?",["CSS|CSS","HTML|HTML","GitHub Pages|GitHub Pages","A favicon|Фавикон"],1,"HTML describes headings, paragraphs, lists, forms and other page content.","HTML тақырып, абзац, тізім, форма сияқты бет мазмұнының құрылымын сипаттайды.");
Q("web","W1","Which technology mainly controls a page's appearance?","Беттің сыртқы көрінісін негізінен не басқарады?",["HTML|HTML","CSS|CSS","The URL|URL","The server name|Сервер атауы"],1,"CSS controls colors, typography, spacing and layout.","CSS түс, қаріп, аралық және орналасуды басқарады.");
Q("web","W1","Which tool can inspect and debug a webpage in the browser?","Браузер ішінде веб бетті тексеретін құрал қайсы?",["Developer Tools|Developer Tools құралдары","A PDF reader|PDF оқу құралы","The title tag|title тегі","A table cell|Кесте ұяшығы"],0,"Browser Developer Tools let you inspect HTML and CSS and test changes.","Браузердің Developer Tools құралы HTML мен CSS-ті көруге және өзгерісті тексеруге көмектеседі.");
Q("web","W1","What is the usual entry file for a GitHub Pages project site?","GitHub Pages жобасының негізгі бастапқы файлы әдетте қалай аталады?",["style.css|style.css","index.html|index.html","image.jpg|image.jpg","README.md|README.md"],1,"A project site normally loads index.html when the site URL is opened.","Сайттың мекенжайын ашқанда әдетте index.html жүктеледі.");

Q("html","W1","What does <!DOCTYPE html> tell the browser?","<!DOCTYPE html> браузерге нені хабарлайды?",["Use HTML5 document mode|HTML5 құжат режимін қолдан","Load an image|Суретті жүкте","Create a heading|Тақырып жаса","Start a CSS rule|CSS ережесін баста"],0,"The doctype declares the document type and helps the browser use standards mode.","Doctype құжат түрін жариялап, браузердің стандартты режимін қолдануына көмектеседі.");
Q("html","W1","What is the difference between a tag and an element?","Тег пен элементтің айырмашылығы қандай?",["They always mean different languages|Олар әрқашан әртүрлі тілдерді білдіреді","A tag is markup such as <p>; an element includes its tags and content|Тег — <p> сияқты белгі, элементке тегтері мен мазмұны кіреді","An element is CSS only|Элемент тек CSS-ке қатысты","A tag is the visible text only|Тег тек көрінетін мәтін"],1,"For example, <p>Hello</p> is a paragraph element; <p> is its opening tag.","Мысалы, <p>Hello</p> — абзац элементі, ал <p> — оның ашылу тегі.");
Q("html","W1","Which element wraps the whole HTML document?","HTML құжатын толық қоршайтын элемент қайсы?",["<body>|<body>","<head>|<head>","<html>|<html>","<main>|<main>"],2,"The <html> root element contains <head> and <body>.","Түбір <html> элементінің ішінде <head> және <body> орналасады.");
Q("html","W1","Where do the page title and stylesheet links normally go?","Бет атауы мен стиль файлдарына сілтемелер әдетте қайда жазылады?",["Inside <head>|<head> ішінде","Inside <footer>|<footer> ішінде","Inside <table>|<table> ішінде","After </html>|</html> соңында"],0,"Metadata, <title>, and <link rel=\"stylesheet\"> belong in <head>.","Метадерек, <title> және стильге арналған <link> тегі <head> ішінде болады.");
Q("html","W1","Which element contains the visible page content?","Беттің көрінетін мазмұны қай элементте орналасады?",["<meta>|<meta>","<body>|<body>","<title>|<title>","<link>|<link>"],1,"Headings, images and forms that users see go in <body>.","Пайдаланушы көретін тақырып, сурет және формалар <body> ішінде болады.");
Q("html","W1 / A1–A3","What does <title> set?","<title> нені орнатады?",["The main visible heading|Беттегі негізгі көрінетін тақырыпты","Text shown in the browser tab|Браузер қойындысында көрінетін атауды","The footer text|Төменгі бөліктегі мәтінді","The image caption|Сурет түсіндірмесін"],1,"<title> is metadata in the head, not a heading in the page body.","<title> — head ішіндегі дерек; беттегі h1 тақырыбы емес.");
Q("html","A1–A3","What does <html lang=\"en\"> indicate?","<html lang=\"en\"> нені білдіреді?",["The page's main language is English|Беттің негізгі тілі ағылшын тілі","The page is encrypted|Бет шифрланған","All links are external|Барлық сілтеме сыртқы","The page uses Grid|Бетте Grid бар"],0,"The lang attribute declares the document language for browsers and assistive technology.","lang атрибуты браузер мен көмекші құралдарға құжат тілін хабарлайды.");
Q("html","A1–A3","Why include <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">?","Viewport meta тегі не үшін керек?",["To help the page size correctly on mobile screens|Бетті телефон экранының өлшеміне дұрыс бейімдеу үшін","To make every image full width|Әр суретті толық енді ету үшін","To add a search box|Іздеу жолағын қосу үшін","To center a table|Кестені ортаға қою үшін"],0,"The viewport setting lets responsive CSS use the device width as intended.","Viewport параметрі адаптивтік CSS-тің құрылғы еніне сай жұмыс істеуіне көмектеседі.");
Q("html","A3","Which semantic tag marks the main content of a page?","Беттің негізгі мазмұнын қай мағыналы тег белгілейді?",["<main>|<main>","<span>|<span>","<br>|<br>","<option>|<option>"],0,"<main> identifies the primary content of the document.","<main> құжаттың негізгі мазмұнын белгілейді.");
Q("html","A2 / A3","Which semantic tag is most appropriate for a navigation menu?","Навигация мәзіріне қай мағыналы тег лайық?",["<nav>|<nav>","<figure>|<figure>","<thead>|<thead>","<label>|<label>"],0,"<nav> identifies a major group of navigation links.","<nav> негізгі навигациялық сілтемелер тобын белгілейді.");
Q("html","W2","What is the usual difference between <div> and <span>?","<div> пен <span> әдетте қалай ерекшеленеді?",["<div> is block-level; <span> is inline|<div> блоктық, <span> жол ішіндегі элемент","<span> is a table row|<span> — кесте жолы","<div> only holds images|<div> тек суреттерге арналған","There is no layout difference by default|Бастапқы орналасуында айырмашылық жоқ"],0,"By default, div starts a block; span flows within a line of text.","Әдепкіде div бөлек блок болып, span мәтін жолының ішінде орналасады.");
Q("html","A3","What is <section> used for?","<section> не үшін қолданылады?",["A thematic group of page content|Бет мазмұнының тақырыптық бөлімі","A selectable form option|Формадағы таңдауға болатын нұсқа","A table column|Кесте бағаны","An image file|Сурет файлы"],0,"A section groups related content, often with its own heading.","Section өзара байланысты мазмұнды, көбіне жеке тақырыппен бірге топтайды.");
Q("html","A3","What does <aside> usually represent?","<aside> әдетте нені білдіреді?",["Related supporting content|Негізгі мазмұнға қатысты қосымша ақпаратты","A form submit button|Форма жіберу батырмасын","The HTML root|HTML түбірін","The page title in the tab|Қойындыдағы бет атауын"],0,"Aside is for related content such as a sidebar or tip.","Aside — бүйірлік панель не кеңес сияқты қосымша мазмұнға арналған.");

Q("content","W1","Which heading is the highest-level heading?","Ең жоғары деңгейдегі тақырып қайсы?",["<h6>|<h6>","<h1>|<h1>","<p>|<p>","<title>|<title>"],1,"Headings run from h1 (highest) to h6 (lowest).","Тақырыптар h1 (ең жоғары) мен h6 (ең төмен) арасында болады.");
Q("content","W1","Which tag creates a paragraph?","Қай тег абзац жасайды?",["<p>|<p>","<br>|<br>","<span>|<span>","<hr>|<hr>"],0,"<p> marks a paragraph of text.","<p> мәтін абзацын белгілейді.");
Q("content","W1","Which tag inserts a line break without starting a new paragraph?","Жаңа абзац бастамай, жаңа жолға түсіретін тег қайсы?",["<hr>|<hr>","<br>|<br>","<li>|<li>","<tr>|<tr>"],1,"<br> breaks the current line; <p> is for paragraphs.","<br> жолды ауыстырады, ал <p> абзацқа арналған.");
Q("content","W1","What does <hr> represent?","<hr> нені білдіреді?",["A thematic break, usually displayed as a horizontal rule|Тақырыптық бөліну, әдетте көлденең сызық","A heading row|Тақырып жолы","A hidden radio input|Жасырын радио батырма","A link to another page|Басқа бетке сілтеме"],0,"<hr> marks a thematic break between sections of content.","<hr> мазмұн бөліктерінің арасындағы тақырыптық бөлінуді білдіреді.");
Q("content","W1 / A1–A3","Which HTML creates a link to another page?","Басқа бетке сілтеме қай HTML арқылы жасалады?",["<a href=\"places.html\">Places</a>|<a href=\"places.html\">Places</a>","<img src=\"places.html\">|<img src=\"places.html\">","<p href=\"places.html\">Places</p>|<p href=\"places.html\">Places</p>","<link src=\"places.html\">|<link src=\"places.html\">"],0,"The anchor <a> uses href for the destination.","<a> сілтемесі баратын мекенжайды href атрибутында сақтайды.");
Q("content","W1 / A1–A3","Which attribute gives an <img> its file path?","<img> тегі сурет файлының жолын қай атрибуттан алады?",["href|href","src|src","alt|alt","id|id"],1,"src is the source path; alt is alternative text.","src — сурет файлының жолы; alt — балама мәтін.");
Q("content","A1–A3","Why write meaningful alt text for an image?","Суретке мағыналы alt мәтін не үшін жазылады?",["It describes the image if it cannot load and for screen readers|Сурет ашылмаса және экран оқитын құралдар үшін сипаттайды","It automatically changes the image size|Сурет өлшемін автоматты өзгертеді","It replaces the src attribute|src атрибутын алмастырады","It adds a border|Жиек қосады"],0,"alt provides a text alternative to image content.","alt сурет мазмұнына мәтіндік балама береді.");
Q("content","A3","Which pair semantically groups an image and its caption?","Сурет пен оның атауын мағыналық түрде топтайтын жұп қайсы?",["<figure> and <figcaption>|<figure> және <figcaption>","<table> and <td>|<table> және <td>","<label> and <option>|<label> және <option>","<head> and <meta>|<head> және <meta>"],0,"A figure can contain media; figcaption is its caption.","Figure суретті қамтиды, figcaption оның түсіндірме жазуы болады.");
Q("content","A3","What does loading=\"lazy\" on an image request?","Суреттегі loading=\"lazy\" нені сұрайды?",["Delay loading until the image is near the viewport|Сурет экранға жақындағанда ғана жүктеу","Make the image transparent|Суретті мөлдір ету","Hide alt text|alt мәтінді жасыру","Turn the image into a link|Суретті сілтемеге айналдыру"],0,"Lazy loading can defer off-screen images until needed.","Lazy loading экраннан тыс суреттерді қажет болған кезде жүктеуі мүмкін.");
Q("content","A2 / A3","What does href=\"#gallery\" target?","href=\"#gallery\" қайда апарады?",["An element on the same page with id=\"gallery\"|Сол беттегі id=\"gallery\" элементіне","A CSS class named gallery|gallery атты CSS класына","A file named gallery.css|gallery.css файлына","Every image on the page|Беттегі барлық суретке"],0,"A # fragment points to the matching id in the current document.","# бөлігі ағымдағы құжаттағы сәйкес id-і бар элементке апарады.");
Q("content","A1 / A2","What does text-decoration: none usually do to a link?","text-decoration: none сілтемеге әдетте не істейді?",["Removes its underline|Астындағы сызықты алып тастайды","Makes it unclickable|Басылмайтын етеді","Moves it to the right|Оңға жылжытады","Changes its URL|Мекенжайын өзгертеді"],0,"It removes text decoration such as the default underline, but the link still works.","Әдепкі астыңғы сызық сияқты безендіруді алып тастайды, бірақ сілтеме жұмыс істей береді.");

Q("tables","W1","Which HTML creates a bulleted list?","Маркерлі тізімді қай HTML жасайды?",["<ul><li>Item</li></ul>|<ul><li>Item</li></ul>","<ol><p>Item</p></ol>|<ol><p>Item</p></ol>","<table><li>Item</li></table>|<table><li>Item</li></table>","<tr><td>Item</td></tr>|<tr><td>Item</td></tr>"],0,"ul is an unordered list; each entry is an li.","ul — реттелмеген тізім, әр бөлігі li болады.");
Q("tables","W1","Which tag makes a numbered list?","Нөмірленген тізімді қай тег жасайды?",["<ul>|<ul>","<ol>|<ol>","<li>|<li>","<dl>|<dl>"],1,"ol means ordered list; li marks each list item.","ol — реттелген тізім, li — әр тізім элементі.");
Q("tables","W1 / A1","What does <li> represent?","<li> нені білдіреді?",["One list item|Тізімнің бір элементі","One table row|Кестенің бір жолы","A link image|Сілтеме суреті","A CSS line|CSS жолы"],0,"li is a list item inside ul or ol.","li — ul немесе ol ішіндегі тізім элементі.");
Q("tables","W1 / A1 / A3","Which element starts a table row?","Кесте жолын қай элемент бастайды?",["<td>|<td>","<th>|<th>","<tr>|<tr>","<caption>|<caption>"],2,"tr means table row; it contains th or td cells.","tr — кесте жолы; оның ішінде th не td ұяшықтары болады.");
Q("tables","W1 / A1 / A3","What is the difference between <th> and <td>?","<th> пен <td> айырмашылығы қандай?",["th is a header cell; td is a data cell|th — тақырып ұяшығы, td — дерек ұяшығы","th is a column; td is a row|th — баған, td — жол","th is CSS; td is HTML|th — CSS, td — HTML","Both create whole tables|Екеуі де толық кесте жасайды"],0,"Both are cells inside a tr; th labels data, td contains data.","Екеуі де tr ішіндегі ұяшық; th деректі атайды, td деректі сақтайды.");
Q("tables","W1 / A3","What does <caption> provide for a table?","<caption> кестеге не береді?",["A table title or description|Кесте атауын немесе сипаттамасын","A new row|Жаңа жол","A column border|Баған жиегін","A form label|Форма белгісін"],0,"caption describes the table as a whole.","caption бүкіл кестені сипаттайды.");
Q("tables","W1 / A3","What is the purpose of <thead>, <tbody>, and <tfoot>?","<thead>, <tbody>, <tfoot> не үшін керек?",["Group the header, body, and footer rows|Тақырып, негізгі және қорытынды жолдарды топтау","Set three table colors automatically|Үш кесте түсін автоматты орнату","Create three separate tables|Үш бөлек кесте жасау","Make the table responsive automatically|Кестені автоматты адаптивті ету"],0,"These elements give structure to different table row groups.","Бұл элементтер кестедегі әртүрлі жол топтарына құрылым береді.");
Q("tables","W1 / A1","What does colspan=\"2\" on a table cell mean?","Кесте ұяшығындағы colspan=\"2\" нені білдіреді?",["The cell spans two columns|Ұяшық екі бағанның орнын алады","The cell spans two rows|Ұяшық екі жолдың орнын алады","The table has exactly two rows|Кестеде дәл екі жол бар","The cell has a 2px border|Ұяшық жиегі 2px"],0,"colspan controls how many columns one cell covers.","colspan бір ұяшық қанша бағанды қамтитынын көрсетеді.");
Q("tables","W1","What does rowspan=\"3\" do?","rowspan=\"3\" не істейді?",["Makes a cell cover three rows|Ұяшықты үш жолға созады","Makes three columns|Үш баған жасайды","Adds three captions|Үш атау қосады","Adds 3px padding|3px ішкі аралық қосады"],0,"rowspan controls how many rows one cell covers.","rowspan бір ұяшық қанша жолды қамтитынын көрсетеді.");
Q("tables","W1 / A3","What does scope=\"col\" on a <th> identify?","<th> ішіндегі scope=\"col\" нені көрсетеді?",["The header describes a column|Тақырып бір бағанды сипаттайды","The header describes the whole page|Тақырып бүкіл бетті сипаттайды","The table has a blue color|Кесте көк түсті","The cell spans columns|Ұяшық бағандарға созылады"],0,"scope helps associate header cells with the data they label.","scope тақырып ұяшығын өзі белгілейтін деректермен байланыстырады.");
Q("tables","A1 / A3","What does border-collapse: collapse do?","border-collapse: collapse не істейді?",["Combines touching table cell borders into single borders|Жанасқан ұяшық жиектерін бір сызыққа біріктіреді","Hides the whole table|Кестені толық жасырады","Removes all text|Барлық мәтінді өшіреді","Makes each cell a flex item|Әр ұяшықты flex элемент етеді"],0,"It merges adjacent table borders instead of showing separate borders.","Ол көршілес ұяшықтардың бөлек жиектерін біріктіреді.");

Q("forms","W1 / A1 / A3","What is the purpose of <form>?","<form> не үшін қолданылады?",["Group user input controls|Пайдаланушы енгізу элементтерін топтау","Create a table|Кесте жасау","Create a CSS selector|CSS селекторын жасау","Insert an image|Сурет кірістіру"],0,"A form contains controls such as input, select and button.","Форма input, select және button сияқты басқару элементтерін қамтиды.");
Q("forms","W2 / A1 / A3","How does <label for=\"email\"> connect to an input?","<label for=\"email\"> input-пен қалай байланысады?",["The input has id=\"email\"|Input-тың id=\"email\" мәні болады","The input has class=\"email\"|Input-тың class=\"email\" мәні болады","The input is type=\"button\"|Input-тың type=\"button\" мәні болады","The form has name=\"email\"|Форманың name=\"email\" мәні болады"],0,"The label's for value must match the input's id.","Label-дің for мәні input-тың id мәнімен сәйкес болуы керек.");
Q("forms","A1 / A3","What does type=\"email\" add compared with type=\"text\"?","type=\"email\" type=\"text\"-ке қарағанда не қосады?",["Email-format validation and suitable input behavior|Электрондық пошта пішімін тексеру және оған сай енгізу","It sends mail automatically|Хатты автоматты жібереді","It hides the text|Мәтінді жасырады","It makes the field optional|Өрісті міндетті емес етеді"],0,"Email inputs expect an email-like address; text inputs accept general text.","Email өрісі пошта мекенжайына ұқсас мән күтеді, text жалпы мәтінді қабылдайды.");
Q("forms","A1 / A3","What does placeholder show?","placeholder нені көрсетеді?",["A hint inside an empty field|Бос өрістің ішіндегі нұсқауды","The field's submitted name|Жіберілетін өріс атауын","The selected answer value|Таңдалған жауап мәнін","A permanent label above the field|Өрістің үстіндегі тұрақты белгіні"],0,"Placeholder is a temporary hint and does not replace a label.","Placeholder — уақытша нұсқау; label орнына жүрмейді.");
Q("forms","A1 / A3","What does required on an input mean?","Input-тегі required нені білдіреді?",["The field must be filled before normal form submission|Әдеттегі жіберуге дейін өріс толтырылуы керек","The field is hidden|Өріс жасырын","The field is read-only|Өріс тек оқуға арналған","The field becomes a button|Өріс батырмаға айналады"],0,"The browser checks a required control before submitting the form.","Браузер форманы жібермей тұрып міндетті өрісті тексереді.");
Q("forms","A3","What does maxlength=\"60\" limit?","maxlength=\"60\" нені шектейді?",["The number of characters a user can enter|Пайдаланушы енгізе алатын таңба санын","The width in pixels|Пиксельдегі енін","The number of form buttons|Форма батырмаларының санын","The font size|Қаріп өлшемін"],0,"maxlength limits the entered text length to 60 characters.","maxlength енгізілген мәтінді 60 таңбамен шектейді.");
Q("forms","A1 / A3","Which input type lets a user choose exactly one option from a group sharing the same name?","Бірдей name бар топтан тек бір нұсқаны таңдауға қай input түрі мүмкіндік береді?",["checkbox|checkbox","radio|radio","email|email","text|text"],1,"Radio buttons with the same name form one mutually exclusive group.","Бірдей name берілген radio батырмалар бір таңдау тобы болады.");
Q("forms","A1","Which input type lets users select several independent options?","Бірнеше тәуелсіз нұсқаны таңдауға қай input түрі арналған?",["radio|radio","checkbox|checkbox","email|email","submit|submit"],1,"Each checkbox can be checked independently.","Әр checkbox бөлек белгілене алады.");
Q("forms","A1 / A3","Which elements make a drop-down list?","Ашылмалы тізімді қай элементтер жасайды?",["<select> with <option>|<select> және <option>","<table> with <tr>|<table> және <tr>","<ul> with <li>|<ul> және <li>","<div> with <span>|<div> және <span>"],0,"select is the control; option provides each choice.","select — басқару элементі, option — әр таңдау нұсқасы.");
Q("forms","A1 / A3","What does an option's value attribute represent?","option элементіндегі value атрибуты нені білдіреді?",["The value used when that option is selected|Сол нұсқа таңдалғанда қолданылатын мәнді","The visible font size|Көрінетін қаріп өлшемін","The number of options|Нұсқалар санын","The select element's width|select элементінің енін"],0,"The option text is shown to the user; value is the associated data value.","Пайдаланушы option мәтінін көреді, ал value — соған тиесілі дерек мәні.");
Q("forms","A1 / A3","Which element is best for multi-line user text?","Пайдаланушының бірнеше жолдық мәтініне қай элемент қолайлы?",["<textarea>|<textarea>","<input type=\"radio\">|<input type=\"radio\">","<option>|<option>","<label>|<label>"],0,"textarea is a multi-line text control.","textarea — бірнеше жолдық мәтін енгізу өрісі.");
Q("forms","A1","What does resize: none do to a textarea?","textarea үшін resize: none не істейді?",["Prevents the user from dragging it to resize|Пайдаланушының сүйреп өлшемін өзгертуіне тыйым салады","Deletes the entered text|Енгізілген мәтінді өшіреді","Makes it invisible|Оны көрінбейтін етеді","Changes its height to zero|Биіктігін нөлге түсіреді"],0,"resize controls whether the user can manually change the textarea size.","resize пайдаланушы textarea өлшемін қолмен өзгерте алатынын басқарады.");
Q("forms","A1 / A3","What does <button type=\"submit\"> do inside a form?","Форма ішіндегі <button type=\"submit\"> не істейді?",["Attempts to submit the form|Форманы жіберуге әрекеттенеді","Always clears the form|Форманы әрқашан тазалайды","Creates a new input|Жаңа input жасайды","Changes the CSS selector|CSS селекторын өзгертеді"],0,"A submit button triggers form submission, subject to validation.","Submit батырмасы тексеруден өткеннен кейін форманы жіберуді бастайды.");
Q("forms","A1 / A3","Why is name useful on a form control?","Форма өрісіне name не үшін керек?",["It identifies the value in submitted form data|Жіберілген форма дерегіндегі мәннің атауын анықтайды","It changes the background color|Фон түсін өзгертеді","It connects CSS automatically|CSS-ті автоматты қосады","It makes the field wider|Өрісті кеңейтеді"],0,"Form submissions use name/value pairs; radio controls also use a shared name to form a group.","Форма name/value жұптарын жібереді; radio батырмалар ортақ name арқылы топталады.");
Q("forms","A3","What does selected on an <option> mean?","<option> элементіндегі selected нені білдіреді?",["That option is chosen initially|Бұл нұсқа бастапқыда таңдалған","That option is required by CSS|Оны CSS міндетті етеді","That option cannot be seen|Ол нұсқа көрінбейді","It creates a new list|Жаңа тізім жасайды"],0,"selected marks an option as the initial selection.","selected нұсқаны бастапқы таңдау ретінде белгілейді.");
Q("forms","A3","What does disabled on a placeholder <option> do?","Алғашқы нұсқадағы disabled не істейді?",["Prevents choosing it as a valid option|Оны жарамды таңдау ретінде белгілеуге жол бермейді","Disables the entire webpage|Бүкіл веб бетті өшіреді","Makes every option bold|Әр нұсқаны қалың етеді","Submits the form|Форманы жібереді"],0,"A disabled placeholder can prompt the user to choose a real option.","Өшірілген бастапқы нұсқа пайдаланушыны нақты жауап таңдауға бағыттайды.");

// WEEK 2 — CSS selectors, appearance, box model, position, and float.
Q("selectors","W2","What is CSS mainly used for?","CSS негізінен не үшін қолданылады?",["Styling and laying out HTML content|HTML мазмұнын безендіру және орналастыру","Storing passwords|Құпиясөздерді сақтау","Creating table data|Кесте деректерін құру","Replacing HTML structure|HTML құрылымын алмастыру"],0,"CSS describes how HTML elements should appear.","CSS HTML элементтерінің қалай көрінетінін сипаттайды.");
Q("selectors","W2","Which is an inline CSS style?","Жол ішіндегі CSS стилі қайсы?",["<p style=\"color:red\">Text</p>|<p style=\"color:red\">Text</p>","p { color: red; } in style.css|style.css ішіндегі p { color: red; }","<style>p { color:red }</style> in head|head ішіндегі <style>p { color:red }</style>","<link rel=\"icon\">|<link rel=\"icon\">"],0,"Inline CSS is written directly in an element's style attribute.","Жол ішіндегі CSS элементтің style атрибутына тікелей жазылады.");
Q("selectors","W2","Where is internal CSS written?","Ішкі CSS қайда жазылады?",["In a <style> element, usually in <head>|Әдетте <head> ішіндегі <style> элементіне","Only in an image file|Тек сурет файлына","Only in the browser URL|Тек браузер мекенжайына","Inside the alt attribute|alt атрибутына"],0,"An internal stylesheet uses the style element in the HTML document.","Ішкі стиль HTML құжатындағы style элементімен жазылады.");
Q("selectors","W2 / A1–A3","Which HTML connects an external CSS file?","Сыртқы CSS файлын қандай HTML қосады?",["<link rel=\"stylesheet\" href=\"styles.css\">|<link rel=\"stylesheet\" href=\"styles.css\">","<img src=\"styles.css\">|<img src=\"styles.css\">","<a src=\"styles.css\">|<a src=\"styles.css\">","<script href=\"styles.css\">|<script href=\"styles.css\">"],0,"The link element with rel=stylesheet points to the CSS file via href.","rel=stylesheet бар link элементі CSS файлын href арқылы көрсетеді.");
Q("selectors","W2","Which selector targets every <p> element?","Барлық <p> элементін қай селектор таңдайды?",["p|p",".p|.p","#p|#p","*p|*p"],0,"An element selector uses the tag name without . or #.","Элемент селекторы тег атауын нүкте мен # белгісінсіз жазады.");
Q("selectors","W2","Which selector targets class=\"card\"?","class=\"card\" үшін селектор қайсы?",["card|card","#card|#card",".card|.card","*card|*card"],2,"A class selector starts with a dot.","Класс селекторы нүктеден басталады.");
Q("selectors","W2","Which selector targets id=\"header\"?","id=\"header\" үшін селектор қайсы?",[".header|.header","#header|#header","header|header","@header|@header"],1,"An ID selector starts with #.","ID селекторы # белгісінен басталады.");
Q("selectors","W2 / A2","What does the universal selector * match?","Әмбебап * селекторы нені таңдайды?",["All elements|Барлық элементті","Only headings|Тек тақырыптарды","Only links|Тек сілтемелерді","Only elements with an ID|Тек ID бар элементтерді"],0,"* matches every element; it is often used for box-sizing resets.","* барлық элементке сәйкес келеді; box-sizing орнату үшін жиі қолданылады.");
Q("selectors","W2","In a simple specificity comparison, which wins: p, .text, or #title?","Қарапайым specificity салыстыруында p, .text, #title ішінен қайсы басым?",["p|p",".text|.text","#title|#title","They are equal|Бәрі тең"],2,"An ID selector is more specific than a class or element selector.","ID селекторы класс пен элемент селекторынан нақтырақ.");
Q("selectors","W2","Which normally has the highest priority among these?","Мына нұсқалардың ішінде әдетте қайсы басым?",["Element selector|Элемент селекторы","Class selector|Класс селекторы","ID selector|ID селекторы","Inline style attribute|Жол ішіндегі style атрибуты"],3,"Within this basic comparison, inline style beats ID, class and element rules.","Бұл қарапайым салыстыруда inline style ID, класс және элемент ережелерінен басым.");
Q("selectors","W2","How are class and id normally used?","class пен id әдетте қалай қолданылады?",["A class can be reused; an id should be unique in the page|Класс қайталана алады, id бетте бірегей болуы керек","Both must be unique|Екеуі де бірегей болуы керек","Only id can be styled|Тек id стильденеді","Only class can be used by HTML|HTML тек class қолданады"],0,"Many elements may share one class; an id identifies one element.","Бірнеше элемент бір класты қолдана алады; id бір элементті белгілейді.");
Q("selectors","A1 / A3","What does .radio label select?",".radio label нені таңдайды?",["Any label inside an element with class radio|radio класы бар элементтің ішіндегі барлық label","An element with both class radio and tag label only|Бір мезгілде radio класы және label тегі бар элементті ғана","Only the element whose id is radio|Тек id-і radio болатын элементті","Every radio input on the page|Беттегі барлық radio input-ты"],0,"A space in a selector means a descendant relationship.","Селектордағы бос орын ішіндегі ұрпақ элементті білдіреді.");
Q("selectors","A1 / A3","What does .card:hover select?",".card:hover нені таңдайды?",["A card while the pointer is over it|Меңзер үстінде тұрған card элементін","All cards after a click|Басылғаннан кейінгі барлық card-тарды","Only hidden cards|Тек жасырын card-тарды","The card's parent|Card-тың ата-анасын"],0,":hover is a pseudo-class for the pointer-over state.",":hover — меңзер элементтің үстінде болғандағы күйді білдіретін псевдокласс.");
Q("selectors","A1","What does tr:nth-child(even) select?","tr:nth-child(even) нені таңдайды?",["Even-positioned tr siblings|Жұп реттік нөмірдегі tr элементтерін","Every second td inside one row|Бір жолдағы әр екінші td-ні","Only the first row|Тек бірінші жолды","All rows with an even number of cells|Ұяшық саны жұп жолдарды"],0,"nth-child(even) matches elements in even sibling positions.","nth-child(even) бір деңгейдегі элементтердің жұп орындарын таңдайды.");
Q("selectors","A2 / A3","What does :focus-visible style?",":focus-visible нені стильдейді?",["An element when keyboard focus should be visibly indicated|Пернетақта фокусы анық көрсетілуі керек элементті","Only an element under the mouse|Тек меңзер астындағы элементті","All hidden elements|Барлық жасырын элементті","The first child only|Тек бірінші ұрпақ элементті"],0,"It is useful for a visible keyboard focus outline.","Бұл пернетақтамен басқарғанда фокус шекарасын айқын көрсетуге пайдалы.");
Q("selectors","A2 / A3","What does :root commonly hold in your CSS?","Жобадағы :root ішінде көбіне не сақталады?",["Reusable CSS custom properties such as --ink|--ink сияқты қайта қолданылатын CSS айнымалылары","All image files|Барлық сурет файлдары","Only table cells|Тек кесте ұяшықтары","The page URL|Бет мекенжайы"],0,":root targets the document root and is a common place for CSS variables.",":root құжат түбірін таңдайды және CSS айнымалыларын сақтауға ыңғайлы.");
Q("selectors","A2 / A3","How is a CSS custom property used after --sea: #146b74 is defined?","--sea: #146b74 анықталғаннан кейін ол қалай қолданылады?",["color: var(--sea);|color: var(--sea);","color: --sea;|color: --sea;","color: variable(sea);|color: variable(sea);","color: #--sea;|color: #--sea;"],0,"var(--sea) reads the custom property's value.","var(--sea) CSS айнымалысының мәнін оқиды.");
Q("selectors","A2 / A3","What does [aria-current=\"page\"] select?","[aria-current=\"page\"] нені таңдайды?",["Elements whose aria-current attribute equals page|aria-current атрибуты page мәніне тең элементтерді","All page elements|Беттегі барлық элементтерді","Every aria label|Барлық aria label-ді","Only a CSS class called page|Тек page атты CSS класты"],0,"Square brackets are an attribute selector; your navbar uses it for the current page.","Тік жақша — атрибут селекторы; навбарда ағымдағы бетті белгілеуге қолданылған.");

Q("style","W2","Which CSS property changes text color?","Мәтін түсін қай CSS қасиеті өзгертеді?",["color|color","background-color|background-color","border-radius|border-radius","font-family|font-family"],0,"color controls the foreground text color.","color мәтіннің алдыңғы түсін басқарады.");
Q("style","W2","Which CSS property changes an element's background color?","Элементтің фон түсін қай CSS қасиеті өзгертеді?",["color|color","background-color|background-color","text-align|text-align","margin|margin"],1,"background-color fills the element's background.","background-color элемент фонын бояйды.");
Q("style","W2","What does #ff0000 represent in CSS?","CSS-тегі #ff0000 нені білдіреді?",["A red hexadecimal color|Он алтылық форматтағы қызыл түс","A font size|Қаріп өлшемі","An ID selector only|Тек ID селекторы","A 0px border|0px жиек"],0,"Hex colors use # followed by red, green and blue channel values.","Hex түс # белгісінен кейін қызыл, жасыл, көк арна мәндерін қолданады.");
Q("style","W2","In rgba(255, 0, 0, 0.5), what does 0.5 control?","rgba(255, 0, 0, 0.5) ішіндегі 0.5 нені басқарады?",["Opacity (alpha)|Мөлдірлікті (alpha)","Font weight|Қаріп қалыңдығын","Border width|Жиек енін","Row count|Жол санын"],0,"The alpha channel 0.5 makes the red color semi-transparent.","Alpha 0.5 қызыл түсті жартылай мөлдір етеді.");
Q("style","W2","What does hsl(0, 100%, 50%) describe?","hsl(0, 100%, 50%) нені сипаттайды?",["Hue, saturation, and lightness|Реңк, қанықтық және ашықтық","Height, size, and line count|Биіктік, өлшем және жол саны","HTML, style, and link|HTML, стиль және сілтеме","Header, sidebar, and layout|Тақырып, бүйір панель және орналасу"],0,"HSL is another way to write a color.","HSL — түсті жазудың тағы бір тәсілі.");
Q("style","W2","Which property selects a typeface such as Arial?","Arial сияқты қаріпті қай қасиет таңдайды?",["font-family|font-family","font-weight|font-weight","line-height|line-height","text-decoration|text-decoration"],0,"font-family lists preferred fonts and fallbacks.","font-family қолданылатын қаріптер мен баламаларын көрсетеді.");
Q("style","W2 / A1","What does font-weight: bold do?","font-weight: bold не істейді?",["Makes text heavier|Мәтінді қалың етеді","Moves text to the right|Мәтінді оңға жылжытады","Adds outer spacing|Сыртқы аралық қосады","Sets the background|Фонды орнатады"],0,"font-weight controls the thickness of the text strokes.","font-weight әріп сызықтарының қалыңдығын басқарады.");
Q("style","W2 / A1","What does text-align: center do?","text-align: center не істейді?",["Centers inline content inside its container|Контейнер ішіндегі жолдық мазмұнды ортаға туралайды","Centers the block itself horizontally|Блоктың өзін көлденең ортаға қояды","Makes every letter uppercase|Әр әріпті бас әріпке айналдырады","Adds padding to both sides|Екі жаққа padding қосады"],0,"text-align centers text and inline content, not the block's own box.","text-align мәтін мен жол ішіндегі мазмұнды туралайды, блоктың өзін емес.");
Q("style","A1 / A3","What does line-height: 1.6 mean?","line-height: 1.6 нені білдіреді?",["Line height is 1.6 times the element's font size|Жол биіктігі қаріп өлшемінің 1.6 есесі","Exactly 1.6 pixels between words|Сөздер арасында дәл 1.6 пиксель","Text is 1.6px wide|Мәтін ені 1.6px","The element has 1.6 columns|Элементте 1.6 баған бар"],0,"A unitless line-height multiplies the element's font size.","Өлшем бірлігі жоқ line-height қаріп өлшеміне көбейтіледі.");
Q("style","W2 / A1","What is the correct box-model order from inside to outside?","Box model іштен сыртқа қарай қалай орналасады?",["Content → padding → border → margin|Мазмұн → padding → border → margin","Margin → content → padding → border|Margin → мазмұн → padding → border","Content → margin → border → padding|Мазмұн → margin → border → padding","Border → content → margin → padding|Border → мазмұн → margin → padding"],0,"The content is surrounded by padding, border, then margin.","Мазмұнды padding, одан кейін border, сыртынан margin қоршайды.");
Q("style","W2 / A1","Which property adds space inside the border?","Жиектің ішіне аралықты қай қасиет қосады?",["margin|margin","padding|padding","float|float","clear|clear"],1,"Padding is the inner space between content and border.","Padding — мазмұн мен жиек арасындағы ішкі аралық.");
Q("style","W2 / A1","Which property adds space outside an element's border?","Элемент жиегінің сыртына аралықты қай қасиет қосады?",["padding|padding","margin|margin","line-height|line-height","border-radius|border-radius"],1,"Margin is the outer space between the element and neighbors.","Margin — элемент пен көршілес элементтер арасындағы сыртқы аралық.");
Q("style","W2 / A1","When does margin: 0 auto commonly center a block horizontally?","margin: 0 auto блокты көлденең ортаға қашан қояды?",["When it has available horizontal space, usually with a set width|Көлденең бос орын бар кезде, әдетте ені берілсе","Only when it has display: inline|Тек display: inline болса","Only inside a table cell|Тек кесте ұяшығында","When font-weight is bold|font-weight bold болса"],0,"Auto left and right margins share the extra space around a sized block.","Сол және оң auto margin белгілі енді блоктың айналасындағы бос орынды бөліседі.");
Q("style","A1 / A2","What does box-sizing: border-box change?","box-sizing: border-box нені өзгертеді?",["Width and height include padding and border|Ен мен биіктікке padding пен border қосылады","It removes all borders|Барлық жиекті алып тастайды","It forces a square shape|Міндетті түрде шаршы жасайды","It makes the element inline|Элементті жол ішіне қояды"],0,"With border-box, declared width includes content, padding and border.","border-box кезінде көрсетілген енге мазмұн, padding және border кіреді.");
Q("style","A1 / A3","What does border-radius: 15px do?","border-radius: 15px не істейді?",["Rounds the corners|Бұрыштарды дөңгелектейді","Adds 15px outer space|15px сыртқы аралық қосады","Makes the border 15px thick|Жиекті 15px қалың етеді","Sets the image width|Сурет енін орнатады"],0,"border-radius controls corner rounding.","border-radius бұрыштардың дөңгеленуін басқарады.");
Q("style","A1 / A3","What does box-shadow add?","box-shadow не қосады?",["A shadow around an element's box|Элемент қорабына көлеңке","A new table row|Жаңа кесте жолын","A background image|Фон суретін","A fixed position|Бекітілген орналасуды"],0,"box-shadow creates a visual shadow around the element.","box-shadow элементтің айналасына көрінетін көлеңке қосады.");
Q("style","A1 / A2","What does max-width: 300px; width: 100% mean together?","max-width: 300px; width: 100% бірге нені білдіреді?",["Use available width but never exceed 300px|Қолдағы енді қолданады, бірақ 300px-тен аспайды","Always be exactly 300px|Әрқашан дәл 300px болады","Always be wider than the parent|Әрқашан ата-анасынан кең болады","Height is 300px|Биіктігі 300px"],0,"The element can shrink with its container but is capped at 300px.","Элемент контейнерімен бірге кішірейе алады, бірақ 300px-тен кең болмайды.");
Q("style","W2 / A1","What is the difference between em and rem?","em мен rem айырмашылығы қандай?",["em is relative to local font sizing; rem to the root font size|em жергілікті қаріп өлшеміне, rem түбір қаріп өлшеміне тәуелді","Both always equal 1px|Екеуі де әрқашан 1px","rem is only for images|rem тек суретке арналған","em is a color unit|em — түс бірлігі"],0,"rem uses the root element's font size; em depends on the element's font context.","rem түбір элементтің қаріп өлшеміне, em элементтің қаріп контекстіне тәуелді.");
Q("style","A1 / A2","What does display: block usually do to an element?","display: block элементке әдетте не істейді?",["Starts a new line and can take a specified width|Жаңа жолдан басталады және берілген енді ала алады","Makes it invisible|Көрінбейтін етеді","Makes it a grid container|Grid контейнері етеді","Prevents margins|Margin қолдануға тыйым салады"],0,"Block boxes typically start on a new line and fill available width by default.","Блок әдетте жаңа жолдан басталып, қолдағы енді толтырады.");
Q("style","A1 / A2","What is useful about display: inline-block?","display: inline-block несімен пайдалы?",["It stays in the text flow while allowing width and height|Мәтін жолында қалып, ен мен биіктікті қабылдайды","It hides an element|Элементті жасырады","It creates table rows|Кесте жолдарын жасайды","It disables hover|hover әсерін өшіреді"],0,"Inline-block combines inline placement with a block-like box size.","Inline-block жол ішіндегі орналасуды және блок сияқты өлшем беруді біріктіреді.");

Q("effects","W2","What is the default position value for most elements?","Көптеген элементтердің әдепкі position мәні қандай?",["static|static","absolute|absolute","fixed|fixed","relative|relative"],0,"Static elements follow the normal document flow.","Static элементтер құжаттың қалыпты орналасу ретімен жүреді.");
Q("effects","W2 / A3","What does position: relative do?","position: relative не істейді?",["Keeps its normal place but can shift relative to it|Қалыпты орнын сақтайды, бірақ өз орнына қатысты жылжи алады","Always sticks to the viewport|Әрқашан экранға жабысады","Removes the element from the page|Элементті беттен өшіреді","Makes the text centered|Мәтінді ортаға туралайды"],0,"A relatively positioned element remains in normal flow; offsets move its visual position.","Relative элемент қалыпты ағымда қалады, ал ығысу оның көрінетін орнын өзгертеді.");
Q("effects","W2 / A2 / A3","An absolutely positioned caption inside position: relative figure is positioned relative to what?","position: relative figure ішіндегі absolute caption орны немен салыстырылады?",["The nearest positioned ancestor, here the figure|Ең жақын position берілген ата-анаға, мұнда figure","Always the browser tab|Әрқашан браузер қойындысына","The next table row|Келесі кесте жолына","The caption's own text|Caption мәтініне"],0,"Absolute positioning uses the nearest ancestor whose position is not static.","Absolute орналасу position мәні static емес ең жақын ата-ананы тірек етеді.");
Q("effects","W2","What does position: fixed position an element relative to?","position: fixed элементті неге қатысты орналастырады?",["Usually the viewport|Әдетте экранның көрінетін бөлігіне","The nearest table cell|Ең жақын кесте ұяшығына","Only its text baseline|Тек мәтін сызығына","The next sibling|Келесі көршілес элементке"],0,"A fixed element generally stays in the same viewport position while scrolling.","Fixed элемент бет жылжығанда да әдетте экрандағы орнын сақтайды.");
Q("effects","W2 / A1","What does float: left do?","float: left не істейді?",["Moves the box left and allows following content to wrap around it|Қорапты солға жылжытып, кейінгі мазмұнның айнала орналасуына мүмкіндік береді","Centers the box|Қорапты ортаға қояды","Hides the box|Қорапты жасырады","Adds left padding|Сол жаққа padding қосады"],0,"Float moves a box to one side so inline content can wrap around it.","Float қорапты бір жаққа шығарып, мәтіннің оны айнала өтуіне мүмкіндік береді.");
Q("effects","W2 / A1","Why use clear: both after floated columns?","Float бағандарынан кейін clear: both не үшін қолданылады?",["To place the element below floats on both sides|Элементті екі жақтағы float-тардың астына түсіру үшін","To remove all CSS rules|Барлық CSS ережесін өшіру үшін","To make both columns transparent|Екі бағанды мөлдір ету үшін","To double the width|Енді екі есе арттыру үшін"],0,"clear: both prevents the element from sitting beside earlier left or right floats.","clear: both элементтің алдыңғы сол/оң float-тың жанында тұруына жол бермейді.");
Q("effects","A1 / A2 / A3","What does button:hover { background-color: blue; } do?","button:hover { background-color: blue; } не істейді?",["Changes the button background when the pointer is over it|Меңзер батырма үстіне келгенде фон түсін өзгертеді","Changes every button permanently|Әр батырманы тұрақты өзгертеді","Changes the button's text only|Тек батырма мәтінін өзгертеді","Changes the page after form submission|Форма жіберілген соң бетті өзгертеді"],0,"The :hover rule applies only while the button is hovered.",":hover ережесі батырма үстіне меңзер келген кезде ғана қолданылады.");
Q("effects","A2 / A3","What does transition: background-color .2s ease add?","transition: background-color .2s ease не қосады?",["A smooth background-color change lasting about 0.2 seconds|Фон түсінің шамамен 0.2 секундта бірқалыпты өзгеруін","A permanent blue background|Тұрақты көк фонды","A 0.2px border|0.2px жиекті","A delayed HTML load|HTML жүктелуін кешіктіруді"],0,"Transition animates changes to the named property over the given duration.","Transition аталған қасиеттің өзгерісін көрсетілген уақытта біртіндеп көрсетеді.");
Q("effects","A2 / A3","What does transform: scale(1.05) do to a gallery image?","Галерея суретіне transform: scale(1.05) не істейді?",["Visually enlarges it by 5%|Оны көзге 5% үлкейтеді","Rotates it 5 degrees|Оны 5 градус бұрады","Makes it 5% transparent|Оны 5% мөлдір етеді","Moves it down 5px|Оны 5px төмен жылжытады"],0,"scale(1.05) is a visual transform; the layout space stays the same.","scale(1.05) көрінетін өлшемді арттырады, орналасуға бөлінген орын өзгермейді.");
Q("effects","A2 / A3","What does object-fit: cover do when an image fills a fixed box?","Сурет тұрақты өлшемді қорапты толтырғанда object-fit: cover не істейді?",["Fills the box while preserving proportions, possibly cropping|Пропорцияны сақтап қорапты толтырады, артығы қиылуы мүмкін","Always shows the full image with empty bars|Әрқашан толық суретті бос жолақпен көрсетеді","Distorts the image to fit exactly|Суретті созып бұрмалайды","Hides the image|Суретті жасырады"],0,"Cover scales to fill the box and clips overflow as needed.","Cover қорапты толтыру үшін суретті үлкейтіп, қажет болса артығын қияды.");
Q("effects","A2 / A3","What does overflow: hidden do on a gallery tile?","Галерея ұяшығындағы overflow: hidden не істейді?",["Clips image parts extending beyond the tile|Ұяшық шегінен асқан сурет бөлігін жасырады","Deletes the image file|Сурет файлын өшіреді","Makes the image a link|Суретті сілтеме етеді","Adds a scrollbar|Айналдыру жолағын қосады"],0,"It keeps enlarged images and overlays inside the tile boundary.","Ол үлкейген сурет пен қабаттарды ұяшық шегінде ұстайды.");
Q("effects","A3","What does z-index: 1 help with in a positioned hero?","Position берілген hero ішінде z-index: 1 не үшін керек?",["Places content above a lower background overlay|Мазмұнды фон қабатынан жоғары шығару үшін","Sets font size to 1px|Қаріпті 1px ету үшін","Creates one grid column|Бір grid бағанын жасау үшін","Moves content 1px down|Мазмұнды 1px төмен жылжыту үшін"],0,"z-index controls stacking order of positioned elements.","z-index position берілген элементтердің қабаттасу ретін басқарады.");
Q("effects","A2 / A3","What does opacity: 0 do to an element?","opacity: 0 элементке не істейді?",["Makes it fully transparent while it can still occupy space|Оны толық мөлдір етеді, бірақ орны сақталуы мүмкін","Removes it from the DOM|Оны DOM-нан өшіреді","Sets its width to zero|Енін нөл етеді","Sets its font weight to zero|Қаріп қалыңдығын нөл етеді"],0,"Opacity affects visual transparency, not layout participation.","Opacity көріну мөлдірлігін өзгертеді, орналасудағы орнын міндетті түрде жоймайды.");

// WEEK 3 — Flexbox and Grid; Assignments 2 and 3 apply both methods.
Q("flex","W3","Is Flexbox mainly one-dimensional or two-dimensional?","Flexbox негізінен бір өлшемді ме, екі өлшемді ме?",["One-dimensional: a row or a column|Бір өлшемді: жол немесе баған","Two-dimensional: rows and columns together|Екі өлшемді: жолдар мен бағандар бірге","Only for tables|Тек кестеге арналған","Only for text colors|Тек мәтін түсіне арналған"],0,"Flexbox lays items along one main axis at a time.","Flexbox элементтерді бір негізгі ось бойымен орналастырады.");
Q("flex","W3 / A2","How do you turn a parent into a Flexbox container?","Ата-ана элементті Flexbox контейнеріне қалай айналдырасың?",["display: flex;|display: flex;","position: flex;|position: flex;","float: flex;|float: flex;","grid: flex;|grid: flex;"],0,"display: flex makes direct children flex items.","display: flex тікелей ішіндегі элементтерді flex item етеді.");
Q("flex","W3","Which elements become flex items?","Қай элементтер flex item болады?",["Direct children of the flex container|Flex контейнердің тікелей балалары","Every element on the page|Беттегі барлық элемент","Only images|Тек суреттер","Only grandchildren|Тек немерелері"],0,"Flex layout applies to direct children of the flex container.","Flex орналасуы контейнердің тікелей балаларына қолданылады.");
Q("flex","W3","For flex-direction: row, which direction is the main axis?","flex-direction: row кезінде негізгі ось қай бағытта?",["Horizontal|Көлденең","Vertical|Тігінен","Diagonal|Қиғаш","There is no main axis|Негізгі ось болмайды"],0,"Row lays items along a horizontal main axis in normal writing direction.","Row элементтерді әдеттегі жазу бағытында көлденең негізгі оське орналастырады.");
Q("flex","W3","What does flex-direction: column do?","flex-direction: column не істейді?",["Stacks items along a vertical main axis|Элементтерді тік негізгі ось бойынша тізеді","Creates a CSS Grid|CSS Grid жасайды","Floats items left|Элементтерді солға float етеді","Adds a table column|Кесте бағанын қосады"],0,"Column changes the main axis from row to vertical.","Column негізгі осьті көлденеңнен тігінен өзгертеді.");
Q("flex","W3 / A2","Which property distributes flex items along the main axis?","Flex элементтерін негізгі ось бойымен қай қасиет орналастырады?",["justify-content|justify-content","align-items|align-items","font-weight|font-weight","object-fit|object-fit"],0,"justify-content controls main-axis distribution.","justify-content негізгі ось бойындағы орналасуды басқарады.");
Q("flex","W3 / A2","Which property aligns flex items on the cross axis?","Flex элементтерін көлденең осьте қай қасиет туралайды?",["align-items|align-items","justify-content|justify-content","grid-column|grid-column","clear|clear"],0,"align-items works across the main axis.","align-items негізгі оське перпендикуляр бағытта жұмыс істейді.");
Q("flex","W3 / A2","What does justify-content: space-between do?","justify-content: space-between не істейді?",["Places first and last items at the ends and space between items|Бірінші және соңғы элементті шетке қойып, арасына бос орын бөледі","Centers every item with no gap|Барлық элементті аралықсыз ортаға қояды","Makes items equal height|Элементтерді тең биіктікте етеді","Wraps items to a new row|Элементтерді жаңа жолға түсіреді"],0,"It distributes remaining main-axis space between items.","Ол негізгі осьтегі қалған бос орынды элементтердің арасына бөледі.");
Q("flex","W3 / A2","What does flex-wrap: wrap allow?","flex-wrap: wrap неге мүмкіндік береді?",["Items can move onto another row or column when needed|Қажет болса элементтер келесі жолға не бағанға өте алады","All items must stay on one line|Барлығы бір жолда қалуы керек","Text becomes bold|Мәтін қалың болады","Items become fixed-position|Элементтер fixed болады"],0,"Wrap lets flex items form multiple lines when there is not enough room.","Wrap орын жетпесе flex элементтердің бірнеше жолға бөлінуіне мүмкіндік береді.");
Q("flex","W3 / A2","What does gap: 20px create in a flex or grid container?","Flex не Grid контейнеріндегі gap: 20px не жасайды?",["20px space between items|Элементтердің арасында 20px аралық","20px outside margin around the container|Контейнер сыртында 20px margin","20px text size|20px мәтін өлшемі","20px border|20px жиек"],0,"gap spaces adjacent layout items; it is not outer margin.","gap көршілес элементтердің арасын ашады; ол сыртқы margin емес.");
Q("flex","W3","What does flex-grow: 1 allow an item to do?","flex-grow: 1 элементке не мүмкіндік береді?",["Take a share of available free space|Бос орынның бір бөлігін алуға","Always shrink to zero|Әрқашан нөлге дейін кішіреюге","Move before all other items|Барлық элементтен бұрын тұруға","Become a table cell|Кесте ұяшығына айналуға"],0,"flex-grow controls how an item expands into remaining space.","flex-grow элементтің қалған бос орынға қарай қалай ұлғаятынын басқарады.");
Q("flex","W3","What does flex-shrink control?","flex-shrink нені басқарады?",["How an item reduces size when space is insufficient|Орын жетпегенде элементтің қалай кішірейетінін","How many children it has|Балаларының санын","The font's weight|Қаріп қалыңдығын","The table border|Кесте жиегін"],0,"The default flex-shrink is 1, so items can shrink if needed.","Әдепкі flex-shrink мәні 1, сондықтан қажет болса элементтер кішірейеді.");
Q("flex","W3 / A2","What does flex-basis set?","flex-basis нені орнатады?",["Initial size along the main axis before growing or shrinking|Ұлғаю не кішірею алдында негізгі ось бойындағы бастапқы өлшемді","The color of the main axis|Негізгі ось түсін","The number of rows|Жол санын","The browser width|Браузер енін"],0,"flex-basis is the starting size considered by flex layout.","flex-basis — Flexbox есептейтін бастапқы өлшем.");
Q("flex","W3 / A2","What does align-self override?","align-self нені алмастырады?",["The container's align-items for one flex item|Бір flex элементі үшін контейнердің align-items мәнін","The font size of all items|Барлық элементтің қаріп өлшемін","The page background|Бет фонын","The HTML language|HTML тілін"],0,"align-self changes cross-axis alignment for one item.","align-self бір элементтің көлденең осьтегі туралануын өзгертеді.");
Q("flex","W3","What does order change on a flex item?","Flex элементіндегі order нені өзгертеді?",["Its visual order within the flex container|Flex контейнер ішіндегі көрінетін ретін","The HTML source order itself|HTML кодындағы бастапқы ретін","Its background color|Фон түсін","Its width unit|Ен бірлігін"],0,"order affects the visual arrangement; it does not rewrite the DOM order.","order көрінетін орналасу ретін өзгертеді, HTML құрылымындағы ретті емес.");
Q("flex","A2","Why might a card body use margin-top: auto on its button?","Карточка батырмасына margin-top: auto не үшін берілуі мүмкін?",["To push the button toward the bottom in a column flex layout|Бағандық flex ішінде батырманы төмен итеру үшін","To center every card on the page|Барлық карточканы бет ортасына қою үшін","To remove hover|hover әсерін өшіру үшін","To make the button invisible|Батырманы жасыру үшін"],0,"An auto top margin takes remaining vertical space in a column flex container.","Бағандық flex контейнерінде auto жоғарғы margin қалған тік бос орынды алады.");

Q("grid","W3","Is CSS Grid mainly one-dimensional or two-dimensional?","CSS Grid негізінен бір өлшемді ме, екі өлшемді ме?",["Two-dimensional: rows and columns|Екі өлшемді: жолдар мен бағандар","One-dimensional only|Тек бір өлшемді","Only for text|Тек мәтінге арналған","Only for HTML tables|Тек HTML кестелерге арналған"],0,"Grid can organize items in rows and columns at the same time.","Grid элементтерді бір мезгілде жолдар мен бағандарға орналастырады.");
Q("grid","W3 / A2 / A3","How do you make a parent a Grid container?","Ата-ана элементті Grid контейнеріне қалай айналдырасың?",["display: grid;|display: grid;","position: grid;|position: grid;","float: grid;|float: grid;","grid: display;|grid: display;"],0,"display: grid turns its direct children into grid items.","display: grid тікелей балаларын grid item етеді.");
Q("grid","W3","What is a grid track?","Grid track деген не?",["A row or a column|Жол немесе баған","A single character|Бір таңба","Only a border line|Тек жиек сызығы","A browser tab|Браузер қойындысы"],0,"Tracks are the rows and columns defined in a grid.","Track — Grid жүйесіндегі жол не баған.");
Q("grid","W3","What is a grid cell?","Grid cell деген не?",["One unit where a row and column intersect|Жол мен баған қиылысатын бір ұяшық","The entire website|Бүкіл сайт","A CSS class|CSS класы","The empty margin|Бос margin"],0,"A cell is one smallest row-and-column unit.","Cell — жол мен баған қиылысындағы ең кіші бөлік.");
Q("grid","W3","What is a grid line?","Grid line деген не?",["A dividing line between grid tracks|Grid жолдары мен бағандарын бөлетін сызық","An HTML <hr> element|HTML <hr> элементі","A text underline|Мәтін астының сызығы","An external stylesheet|Сыртқы стиль файлы"],0,"Grid lines mark the boundaries used to position items.","Grid line элементтерді орналастыруға қолданылатын шекараны белгілейді.");
Q("grid","W3 / A2","What does grid-template-columns: 1fr 2fr define?","grid-template-columns: 1fr 2fr нені анықтайды?",["Two columns sharing available space in a 1:2 ratio|Бос орынды 1:2 қатынасында бөлетін екі баған","Two rows of equal height|Биіктігі тең екі жол","One column 2px wide|Ені 2px бір баған","Three fixed columns|Үш тұрақты баған"],0,"fr distributes available grid space proportionally.","fr Grid ішіндегі бос орынды пропорциямен бөледі.");
Q("grid","W3 / A2","What does repeat(3, 1fr) mean in grid-template-columns?","grid-template-columns ішіндегі repeat(3, 1fr) нені білдіреді?",["Three equal flexible columns|Ені бірдей үш икемді баған","Three equal rows|Биіктігі тең үш жол","One column three times wider|Үш есе кең бір баған","Three pixels of gap|3px аралық"],0,"repeat(3, 1fr) repeats the 1fr column definition three times.","repeat(3, 1fr) 1fr бағанын үш рет қайталайды.");
Q("grid","W3 / A2","Why use minmax(0, 1fr) for a grid column?","Grid бағанына minmax(0, 1fr) не үшін қолданылады?",["It allows the track to shrink to zero minimum and grow to one fraction|Бағанның ең аз өлшемін 0 етіп, 1fr дейін икемді өсіреді","It forces a 1px column|Бағанды міндетті түрде 1px етеді","It makes the row fixed|Жолды тұрақты етеді","It changes the text color|Мәтін түсін өзгертеді"],0,"minmax defines a minimum and maximum track size; zero avoids some content overflow.","minmax track-тің ең аз және ең көп өлшемін анықтайды; нөл кейбір артық шығуды азайтады.");
Q("grid","W3","What does auto mean as a grid track size?","Grid track өлшеміндегі auto нені білдіреді?",["Size adjusts based on content and available space|Өлшем мазмұн мен бос орынға сай бейімделеді","Track is always zero|Track әрқашан нөл","Track is always 100px|Track әрқашан 100px","Track is hidden|Track жасырын"],0,"auto sizing adapts to the grid context and content.","auto өлшемі мазмұн мен Grid кеңістігіне бейімделеді.");
Q("grid","W3","How does min-content differ from max-content for grid sizing?","Grid өлшемінде min-content пен max-content айырмасы қандай?",["min-content is the smallest intrinsic size; max-content is the largest unwrapped intrinsic size|min-content — мүмкін ең кіші, max-content — жолға бөлінбеген ең үлкен табиғи өлшем","They are both always 0px|Екеуі де әрқашан 0px","They set colors|Олар түс орнатады","They choose row numbers|Олар жол нөмірін таңдайды"],0,"These intrinsic sizes are based on how the content can fit or wrap.","Бұл табиғи өлшемдер мазмұнның сыйып, жолға бөлінуіне қарай есептеледі.");
Q("grid","W3","What does fit-content(300px) do to a grid track?","Grid track үшін fit-content(300px) не істейді?",["Lets it fit content up to a 300px limit|Мазмұнға сай өседі, бірақ 300px шамасымен шектеледі","Always makes it exactly 300px|Әрқашан дәл 300px етеді","Adds 300px padding|300px padding қосады","Creates 300 columns|300 баған жасайды"],0,"fit-content sizes the track to content, constrained by the given limit.","fit-content track-ті мазмұнға сай өлшейді, бірақ берілген шекпен шектейді.");
Q("grid","W3 / A2","Which property sets grid row heights?","Grid жолдарының биіктігін қай қасиет белгілейді?",["grid-template-rows|grid-template-rows","grid-template-columns|grid-template-columns","justify-items|justify-items","flex-basis|flex-basis"],0,"grid-template-rows defines the row tracks.","grid-template-rows жол track-терін анықтайды.");
Q("grid","W3 / A2","What is the difference between row-gap and column-gap?","row-gap пен column-gap айырмашылығы қандай?",["row-gap spaces rows; column-gap spaces columns|row-gap жолдардың, column-gap бағандардың аралығын ашады","Both change font spacing|Екеуі де әріп аралығын өзгертеді","row-gap sets border radius|row-gap бұрыштарды дөңгелектейді","column-gap adds outer margin|column-gap сыртқы margin қосады"],0,"Both set spacing between grid tracks in their respective directions.","Екеуі Grid track-тердің өз бағытындағы аралығын орнатады.");
Q("grid","W3 / A2","What does grid-column: 1 / 3 mean?","grid-column: 1 / 3 нені білдіреді?",["Span from grid line 1 to line 3, covering two columns|1-сызықтан 3-сызыққа дейін, екі бағанды қамтиды","Occupy only the third column|Тек үшінші бағанды алады","Create three rows|Үш жол жасайды","Set a 1px to 3px width|Енін 1px–3px етеді"],0,"Grid lines bound the item's column span.","Grid сызықтары элемент қамтитын баған шегін анықтайды.");
Q("grid","W3","What does grid-row control on an item?","Элементтегі grid-row нені басқарады?",["Which row lines the item spans|Элемент қай жол сызықтарының арасында орналасатынын","The text line height|Мәтін жолының биіктігін","The outer margin|Сыртқы аралықты","The image source|Сурет файлының жолын"],0,"grid-row specifies an item's position or span along grid rows.","grid-row элементтің Grid жолдарындағы орнын не қамту ауқымын белгілейді.");
Q("grid","W3 / A2","What does grid-template-areas define?","grid-template-areas нені анықтайды?",["A named map of the grid layout|Grid орналасуының атаулы картасын","The CSS font family|CSS қаріп түрін","The number of HTML pages|HTML бет санын","A table caption|Кесте атауын"],0,"Assignment 2 maps header, sidebar, main and footer with named areas.","2-үй жұмысында header, sidebar, main және footer атаулы аймақтармен орналастырылған.");
Q("grid","W3 / A2","What does grid-area: sidebar do to an item when the template has a sidebar area?","Үлгіде sidebar аймағы барда grid-area: sidebar не істейді?",["Places the item in the named sidebar area|Элементті sidebar атты аймаққа орналастырады","Makes the item a flex container|Элементті flex контейнері етеді","Adds a border to the sidebar|Бүйір панельге жиек қосады","Changes the page title|Бет атауын өзгертеді"],0,"The item uses a name declared in grid-template-areas.","Элемент grid-template-areas ішінде көрсетілген атауды қолданады.");
Q("grid","W3","Which property aligns all grid items horizontally within their own cells?","Барлық Grid элементін өз ұяшығында көлденең қай қасиет туралайды?",["justify-items|justify-items","align-content|align-content","flex-wrap|flex-wrap","clear|clear"],0,"justify-items controls inline-axis alignment of items within cells.","justify-items элементтердің ұяшық ішіндегі көлденең туралануын басқарады.");
Q("grid","W3","Which property aligns all grid items vertically within their own cells?","Барлық Grid элементін өз ұяшығында тігінен қай қасиет туралайды?",["align-items|align-items","justify-content|justify-content","font-size|font-size","grid-column|grid-column"],0,"align-items controls block-axis alignment of items in their cells.","align-items элементтердің ұяшық ішіндегі тік туралануын басқарады.");
Q("grid","W3","Which property aligns the whole grid horizontally when there is extra container space?","Контейнерде артық орын болса бүкіл Grid-ті көлденең қай қасиет туралайды?",["justify-content|justify-content","justify-items|justify-items","align-self|align-self","flex-shrink|flex-shrink"],0,"justify-content moves the entire grid tracks, while justify-items aligns each item within a cell.","justify-content бүкіл Grid track-терін жылжытады, justify-items әр элементті ұяшығында туралайды.");
Q("grid","W3","Which property aligns the whole grid vertically when there is extra container space?","Контейнерде артық орын болса бүкіл Grid-ті тігінен қай қасиет туралайды?",["align-content|align-content","align-items|align-items","text-align|text-align","grid-row|grid-row"],0,"align-content positions the grid tracks as a group along the block axis.","align-content Grid track-терін тұтас топ ретінде тік бағытта орналастырады.");
Q("grid","W3","Which property aligns only one grid item horizontally within its cell?","Тек бір Grid элементін ұяшықта көлденең қай қасиет туралайды?",["justify-self|justify-self","justify-items|justify-items","align-content|align-content","grid-template-rows|grid-template-rows"],0,"justify-self overrides horizontal item alignment for one grid item.","justify-self бір Grid элементінің көлденең туралануын жеке өзгертеді.");
Q("grid","W3","Can a Grid item itself be a Flexbox container?","Grid элементінің өзі Flexbox контейнері бола ала ма?",["Yes, Grid and Flexbox can be nested|Иә, Grid пен Flexbox бірінің ішінде бірі қолданыла алады","No, a page may use only one layout method|Жоқ, бетте тек бір орналасу тәсілі ғана болады","Only if it is a table|Тек ол кесте болса","Only with inline CSS|Тек inline CSS арқылы"],0,"Use Grid for a page section and Flexbox to align content inside a grid item.","Бет бөлімін Grid-пен, сол ұяшық ішіндегі мазмұнды Flexbox-пен орналастыруға болады.");

Q("responsive","A2 / A3","What does @media (max-width: 680px) mean?","@media (max-width: 680px) нені білдіреді?",["Apply enclosed CSS when the viewport is 680px wide or narrower|Экран ені 680px немесе одан аз болса ішіндегі CSS қолданылады","Apply CSS only to images|CSS тек суреттерге қолданылады","Make the page exactly 680px wide|Бетті дәл 680px енді етеді","Always hide the menu|Мәзірді әрқашан жасырады"],0,"A max-width media query targets a viewport no wider than its breakpoint.","max-width медиа сұрауы шектен аспайтын экран еніне арналған.");
Q("responsive","A2 / A3","Why change a three-column gallery to one column on narrow screens?","Тар экранда үш бағандық галереяны неге бір бағанға ауыстырады?",["To keep images readable without horizontal crowding|Суреттерді тар қыспай, анық көрсету үшін","To remove all images|Барлық суретті өшіру үшін","To prevent scrolling completely|Айналдыруды толық тоқтату үшін","To increase download size|Жүктеу көлемін арттыру үшін"],0,"Responsive CSS adjusts layout to the available viewport width.","Адаптивтік CSS орналасуды экранның қолдағы еніне бейімдейді.");
Q("responsive","A2 / A3","What is a CSS breakpoint?","CSS breakpoint деген не?",["A viewport threshold where layout rules change|Орналасу ережесі өзгеретін экран ені шегі","A broken HTML tag|Бұзылған HTML тегі","A browser error only|Тек браузер қатесі","A table border|Кесте жиегі"],0,"Media queries use breakpoints to switch styles for different screen sizes.","Медиа сұраулар әртүрлі экран үшін стильді ауыстыруға breakpoint қолданады.");
Q("responsive","A3","In Bootstrap, what do .container and .row usually provide?","Bootstrap-та .container мен .row әдетте не береді?",["A responsive content wrapper and a grid row|Адаптивті мазмұн қорабын және тор жолын","An image and a link|Сурет пен сілтемені","A table and a caption|Кесте мен атауын","A CSS ID and selector|CSS ID мен селекторын"],0,"Bootstrap's grid commonly nests rows inside containers and columns inside rows.","Bootstrap торында әдетте container ішінде row, row ішінде col орналасады.");
Q("responsive","A3","What does Bootstrap .col-md-6 usually mean?","Bootstrap-та .col-md-6 әдетте нені білдіреді?",["At medium screens and above, use 6 of 12 grid columns|Орта және кең экранда 12 тор бағанының 6-уын алу","Always use 6 pixels of width|Әрқашан 6px ен","Create exactly 6 rows|Дәл 6 жол жасау","Add 6px margin|6px margin қосу"],0,"Bootstrap uses a 12-column responsive grid; md applies from its medium breakpoint.","Bootstrap 12 бағандық адаптивті торды қолданады; md орта өлшемнен бастап іске қосылады.");
Q("responsive","A3","What does Bootstrap .row-cols-lg-3 request?","Bootstrap-та .row-cols-lg-3 не сұрайды?",["Three columns per row on large screens and wider|Кең экранда бір жолға үш баған","Three rows on every screen|Әр экранда үш жол","A 3px column gap|3px баған аралығы","Three navigation bars|Үш навбар"],0,"row-cols-* sets the number of columns per row at the given breakpoint.","row-cols-* көрсетілген экран өлшемінде бір жолдағы баған санын белгілейді.");
Q("responsive","A3","What does Bootstrap .d-flex do?","Bootstrap-та .d-flex не істейді?",["Sets display: flex|display: flex орнатады","Sets display: none|display: none орнатады","Adds a font|Қаріп қосады","Adds a table|Кесте қосады"],0,"d-flex is a Bootstrap display utility for Flexbox.","d-flex — Flexbox қосатын Bootstrap класы.");
Q("responsive","A3","What does Bootstrap .flex-md-row mean?","Bootstrap-та .flex-md-row нені білдіреді?",["Use row flex direction from medium screens upward|Орта және кең экранда flex бағытын жол ету","Always make an HTML table row|Әрқашан HTML кесте жолын жасау","Move text to the right by 1px|Мәтінді 1px оңға жылжыту","Hide content on phones|Телефонда мазмұнды жасыру"],0,"This responsive utility changes flex-direction at the md breakpoint.","Бұл адаптивті класс md шегінен бастап flex-direction бағытын өзгертеді.");
Q("responsive","A3","What does Bootstrap .ms-auto commonly do in a flex navbar?","Flex навбарында Bootstrap .ms-auto әдетте не істейді?",["Adds auto margin on the start side, pushing links away|Бастапқы жақтағы margin-ді auto етіп, сілтемелерді қарсы жаққа итереді","Sets the menu font size|Мәзір қаріп өлшемін орнатады","Disables the links|Сілтемелерді өшіреді","Centers every image|Әр суретті ортаға қояды"],0,"Auto start margin takes remaining flex space and separates the brand from links.","Бастапқы жақтағы auto margin бос орынды алып, логотип пен сілтемелерді ажыратады.");
Q("responsive","A3","What does Bootstrap .g-3 set in a row?","Bootstrap row ішіндегі .g-3 нені орнатады?",["Gutters, or gaps, between grid columns and rows|Тор бағандары мен жолдарының аралығын","Font weight 3|Қаріп қалыңдығын 3","Three images|Үш сурет","A 3px border|3px жиек"],0,"g-* is Bootstrap's gutter spacing utility.","g-* — Bootstrap-тағы тор элементтерінің аралық класы.");
Q("responsive","A3","Why does the mobile Bootstrap navbar need a toggler button?","Телефондағы Bootstrap навбарына toggler батырмасы не үшін керек?",["To show or hide the collapsed navigation links|Жиналған навигациялық сілтемелерді ашып-жабу үшін","To change the page title|Бет атауын өзгерту үшін","To resize every image|Барлық сурет өлшемін өзгерту үшін","To make a table|Кесте жасау үшін"],0,"The button controls the collapsed menu; Bootstrap's local bundle handles the interaction.","Батырма жиналатын мәзірді басқарады; әрекетті жергілікті Bootstrap файлы орындайды.");
Q("responsive","A2 / A3","What does @media (prefers-reduced-motion: reduce) address?","@media (prefers-reduced-motion: reduce) нені ескереді?",["A user's preference for less animation|Пайдаланушының анимацияны азайту қалауын","Only small screens|Тек шағын экрандарды","Only dark mode|Тек қараңғы режимді","A broken CSS file|Бұзылған CSS файлын"],0,"The projects disable some transitions for users requesting reduced motion.","Жобаларда анимацияны азайтуды қалағандарға кейбір transition өшіріледі.");
Q("responsive","A3","In what order should Bootstrap CSS and your custom stylesheet be linked if your styles should override Bootstrap?","Өз стилің Bootstrap-ты басымдықпен өзгертуі үшін CSS файлдарын қалай қосу керек?",["Bootstrap first, custom CSS after it|Алдымен Bootstrap, кейін өз CSS файлың","Custom CSS first, Bootstrap after it|Алдымен өз CSS файлың, кейін Bootstrap","Only the JavaScript file|Тек JavaScript файлы","Order never matters for equal-specificity rules|Бірдей specificity болса да рет маңызды емес"],0,"For equally specific rules, the later stylesheet can override earlier declarations.","Specificity бірдей ережелерде кейін қосылған стиль алдыңғысын баса алады.");

// Short code-reading questions from the exact styles used across the projects.
Q("html","A1–A3","What does <meta charset=\"utf-8\"> declare?","<meta charset=\"utf-8\"> нені жариялайды?",["The document's character encoding|Құжат таңбаларының кодталуын","The page width|Бет енін","A CSS class|CSS класын","The image format|Сурет пішімін"],0,"UTF-8 supports letters from many languages, including Kazakh.","UTF-8 көптеген тілдің, соның ішінде қазақ тілінің әріптерін қолдайды.");
Q("html","A2 / A3","Which semantic element typically contains a page's closing information?","Беттің қорытынды ақпараты әдетте қай мағыналы элементте болады?",["<footer>|<footer>","<thead>|<thead>","<option>|<option>","<br>|<br>"],0,"Footer commonly contains closing links, credits or copyright information.","Footer көбіне соңғы сілтеме, автор не құқық туралы ақпаратты қамтиды.");
Q("style","W2 / A1","What does font-size: 16px set?","font-size: 16px нені орнатады?",["The text size|Мәтін өлшемін","The border color|Жиек түсін","The outer margin|Сыртқы аралықты","The number of columns|Баған санын"],0,"font-size sets the size of text; px is a CSS pixel unit.","font-size мәтін өлшемін белгілейді; px — CSS пиксель бірлігі.");
Q("style","A1","What does text-align: right do?","text-align: right не істейді?",["Aligns inline content to the right inside its container|Контейнер ішіндегі мәтінді оң жаққа туралайды","Floats the whole container right|Бүкіл контейнерді оңға float етеді","Adds right padding|Оң жаққа padding қосады","Makes the font bold|Қаріпті қалың етеді"],0,"text-align positions text inside the element; it does not move the element's box.","text-align элемент ішіндегі мәтінді туралайды; элемент қорабын жылжытпайды.");
Q("style","A1","What does padding-left: 40px do?","padding-left: 40px не істейді?",["Adds 40px of inner space on the left|Сол жақтан 40px ішкі аралық қосады","Adds 40px outer space on the left|Сол жақтан 40px сыртқы аралық қосады","Moves the element to a new row|Элементті жаңа жолға өткізеді","Makes the element 40px wide|Элемент енін 40px етеді"],0,"Padding is inside the border; padding-left applies only on the left.","Padding жиектің ішінде болады; padding-left тек сол жаққа әсер етеді.");
Q("style","A1","What do margin-top: 15px and margin-bottom: 5px set?","margin-top: 15px және margin-bottom: 5px нені орнатады?",["Outer space above and below the element|Элементтің үсті мен астындағы сыртқы аралықты","Inner space left and right|Сол және оң жақтағы ішкі аралықты","Border widths|Жиек қалыңдығын","Text alignment|Мәтін туралануын"],0,"These margins set outside spacing above and below the box.","Бұл margin мәндері қораптың үсті мен астындағы сыртқы аралықты береді.");
Q("effects","A1","What does cursor: pointer usually signal on a button?","Батырмадағы cursor: pointer әдетте нені көрсетеді?",["A clickable control by showing a hand pointer|Қол белгісін көрсетіп, басылатын элементті білдіреді","A disabled button|Өшірілген батырманы","A text selection cursor|Мәтін таңдау меңзерін","A hidden form|Жасырын форманы"],0,"It changes the pointer appearance over the element.","Ол меңзердің элемент үстіндегі сыртқы түрін өзгертеді.");
Q("effects","A2 / A3","What does display: none do?","display: none не істейді?",["Hides the element and removes its layout space|Элементті жасырып, орналасудағы орнын алып тастайды","Makes it transparent but keeps its space|Оны мөлдір етіп, орнын сақтайды","Adds a shadow|Көлеңке қосады","Centers it|Ортаға қояды"],0,"Unlike opacity: 0, display: none removes the box from layout.","opacity: 0-ден айырмашылығы, display: none қораптың орналасудағы орнын жояды.");
Q("grid","W3","What does align-self do on one grid item?","Бір Grid элементіндегі align-self не істейді?",["Overrides its vertical alignment within its cell|Ұяшық ішіндегі тік туралануын жеке өзгертеді","Sets every column width|Әр бағанның енін белгілейді","Changes all items' font size|Барлық элементтің қаріп өлшемін өзгертеді","Creates a new grid row|Жаңа Grid жолын жасайды"],0,"align-self controls one item's block-axis alignment.","align-self бір элементтің тік бағыттағы туралануын басқарады.");
Q("content","W2","What is a favicon?","Favicon деген не?",["The small icon shown in a browser tab|Браузер қойындысында көрінетін шағын белгі","The largest image in the page|Беттегі ең үлкен сурет","A CSS table border|CSS кесте жиегі","A form submit button|Форма жіберу батырмасы"],0,"A favicon is usually linked in the head with rel=icon.","Favicon әдетте head ішінде rel=icon арқылы қосылады.");

Q("content","A3","What does aria-label give an element?","aria-label элементке не береді?",["An accessible name for assistive technology|Көмекші технологияға арналған түсінікті атау","A visible border automatically|Автоматты көрінетін жиек","A CSS class|CSS класы","A link destination|Сілтеме мекенжайы"],0,"An aria-label can name a control or region when a clear visible label is absent.","aria-label көрінетін атауы жеткіліксіз басқару элементіне не бөлімге түсінікті атау береді.");
Q("content","A3","What does aria-labelledby=\"hero-title\" use?","aria-labelledby=\"hero-title\" нені қолданады?",["The text of the element with id=\"hero-title\" as its accessible name|id=\"hero-title\" элементінің мәтінін қолжетімді атау ретінде","A CSS class named hero-title|hero-title атты CSS класын","An image file|Сурет файлын","A table header row|Кестенің тақырып жолын"],0,"aria-labelledby points to an existing element's id for a label.","aria-labelledby атау алу үшін бар элементтің id мәніне сілтейді.");
Q("content","A3","Why can tabindex=\"0\" be added to a gallery figure?","Галереядағы figure элементіне tabindex=\"0\" не үшін қосылады?",["To make it reachable with the Tab key|Оны Tab пернесімен таңдауға мүмкіндік беру үшін","To put it first in the CSS grid|Оны Grid ішінде бірінші ету үшін","To add a 0px border|0px жиек қосу үшін","To disable its image|Суретін өшіру үшін"],0,"Keyboard focus can then reveal focus styles or a caption.","Пернетақта фокусы сол элементтің стилін не сурет жазуын көрсете алады.");
Q("tables","A3","What does scope=\"row\" mean on a table header cell?","Кесте тақырып ұяшығындағы scope=\"row\" нені білдіреді?",["It labels the data in that row|Ол сол жолдағы деректерді атайды","It creates a new row|Жаңа жол жасайды","It spans all rows|Барлық жолдарды қамтиды","It changes the row color|Жол түсін өзгертеді"],0,"A row header identifies cells across its row.","Жол тақырыбы сол жолдағы ұяшықтардың мағынасын түсіндіреді.");
Q("selectors","A2","What does .grid-page > .site-header select?",".grid-page > .site-header нені таңдайды?",["A site-header that is a direct child of grid-page|grid-page элементінің тікелей баласы болатын site-header","Any site-header anywhere on the page|Беттегі кез келген site-header","The first site-header after grid-page|grid-page-тен кейінгі бірінші site-header","Only the grid-page itself|Тек grid-page-тің өзін"],0,"The > combinator selects only direct children.","> белгісі тек тікелей бала элементті таңдайды.");
Q("selectors","A3","What does .fact-list li + li select?",".fact-list li + li нені таңдайды?",["An li immediately after another li inside fact-list|fact-list ішіндегі басқа li-ден кейін бірден келетін li","The first li only|Тек бірінші li","Every plus sign in text|Мәтіндегі әр + таңбасы","The fact-list parent only|Тек fact-list ата-анасы"],0,"The + combinator means an adjacent sibling.","+ белгісі бірден кейін тұрған көршілес элементті білдіреді.");
Q("selectors","A1","Why might .container::after be used with floats?","Float-пен бірге .container::after не үшін қолданылуы мүмкін?",["To create a clearing pseudo-element after the content|Мазмұн соңына float-ты тазалайтын псевдоэлемент қосу үшін","To replace all child elements|Барлық бала элементті алмастыру үшін","To change the page URL|Бет URL-ын өзгерту үшін","To add a form button|Форма батырмасын қосу үшін"],0,"With content, display and clear: both, ::after can make a container enclose its floats.","content, display және clear: both арқылы ::after контейнердің float элементтерін қамтуына көмектеседі.");
Q("selectors","A2","What does .site-nav a:hover, .site-nav a:focus-visible mean?",".site-nav a:hover, .site-nav a:focus-visible нені білдіреді?",["Apply the same rule to both states|Бір ережені екі күйге де қолдану","Select only links in both states at once|Тек екі күйде бірдей тұрған сілтемені таңдау","Make the link a table|Сілтемені кестеге айналдыру","Remove keyboard focus|Пернетақта фокусын алып тастау"],0,"A comma separates selector alternatives that share one declaration block.","Үтір бір CSS ережесін бөлісетін селекторларды бөледі.");
Q("style","A2 / A3","What does letter-spacing: .1em change?","letter-spacing: .1em нені өзгертеді?",["Space between characters|Әріптердің арасындағы аралықты","Space between paragraphs|Абзацтардың арасындағы аралықты","The line height|Жол биіктігін","The border thickness|Жиек қалыңдығын"],0,"letter-spacing adjusts tracking between letters.","letter-spacing әріптердің бір-бірінен арақашықтығын реттейді.");
Q("style","A2 / A3","What does text-transform: uppercase do?","text-transform: uppercase не істейді?",["Displays text in capital letters|Мәтінді бас әріппен көрсетеді","Changes the HTML source text permanently|HTML мәтінін тұрақты өзгертеді","Moves text upward|Мәтінді жоғары жылжытады","Makes text bold|Мәтінді қалың етеді"],0,"It affects presentation; it does not edit the HTML source.","Ол тек көрініске әсер етеді, HTML ішіндегі мәтінді өзгертпейді.");
Q("style","A2","What does white-space: nowrap prevent?","white-space: nowrap неге жол бермейді?",["Text wrapping to a new line at normal spaces|Мәтіннің қалыпты бос орыннан жаңа жолға ауысуына","Changing text color|Мәтін түсін өзгертуге","All scrolling|Барлық айналдыруға","Applying a background|Фон қолдануға"],0,"It keeps text such as a short logo label on one line.","Ол қысқа логотип мәтіні сияқты жазуды бір жолда ұстайды.");
Q("style","A2","What does list-style: none remove from a navigation list?","Навигация тізімінде list-style: none нені алып тастайды?",["Default bullets or numbers|Әдепкі маркерді не нөмірді","The list items themselves|Тізім элементтерінің өзін","All links|Барлық сілтемені","The list's background|Тізім фонын"],0,"The list remains semantic, but the visual markers are removed.","Тізімнің мағынасы сақталады, тек көрінетін маркерлері өшеді.");
Q("style","A2","What does padding-block: 20px affect?","padding-block: 20px қай жақтарға әсер етеді?",["Top and bottom inner spacing in normal horizontal writing|Әдеттегі жазылымда үстіңгі және астыңғы ішкі аралыққа","Left and right outer spacing|Сол және оң сыртқы аралыққа","The font size|Қаріп өлшеміне","The image ratio|Сурет қатынасына"],0,"padding-block is a logical property for the block-axis padding.","padding-block — блок осі бойындағы ішкі аралыққа арналған логикалық қасиет.");
Q("style","A2","What does margin-inline: auto commonly do for a width-limited container?","Ені шектелген контейнерге margin-inline: auto әдетте не істейді?",["Centers it horizontally by balancing side margins|Екі жақтағы margin-ді теңестіріп, көлденең ортаға қояды","Adds automatic top margin|Жоғарғы margin-ді автоматты етеді","Makes it fill the viewport height|Экран биіктігін толтырады","Turns it into a link|Оны сілтемеге айналдырады"],0,"On a horizontal page, inline margins are left and right margins.","Кәдімгі көлденең жазылымда inline margin — сол және оң жақ margin.");
Q("style","A2","What does min-height: 100vh mean?","min-height: 100vh нені білдіреді?",["Minimum height equals the viewport height|Ең аз биіктік экранның көрінетін биіктігіне тең","Maximum width equals 100 pixels|Ең үлкен ен 100 пиксель","Exactly 100 rows|Дәл 100 жол","Font size is 100%|Қаріп өлшемі 100%"],0,"vh is a viewport-height unit; 100vh is the full viewport height.","vh — экран биіктігінің бірлігі; 100vh — толық көрінетін биіктік.");
Q("style","A2","What does aspect-ratio: 16 / 10 do for an image box?","Сурет қорабына aspect-ratio: 16 / 10 не істейді?",["Keeps a 16:10 width-to-height proportion|Ен мен биіктіктің 16:10 қатынасын сақтайды","Sets width to 16px and height to 10px|Енін 16px, биіктігін 10px етеді","Adds 16px padding and 10px margin|16px padding және 10px margin қосады","Creates 16 grid columns|16 Grid бағанын жасайды"],0,"aspect-ratio sets the preferred width-to-height relationship.","aspect-ratio ен мен биіктіктің қалаулы қатынасын белгілейді.");
Q("style","A2 / A3","What does clamp(2rem, 4vw, 2.8rem) do for font-size?","font-size үшін clamp(2rem, 4vw, 2.8rem) не істейді?",["Uses fluid 4vw sizing bounded between 2rem and 2.8rem|4vw бойынша өзгереді, бірақ 2rem–2.8rem аралығында қалады","Always uses 4px|Әрқашан 4px қолданады","Changes the font family|Қаріп түрін өзгертеді","Creates three font files|Үш қаріп файлын жасайды"],0,"clamp(min, preferred, max) keeps a responsive value within limits.","clamp(ең аз, қалаулы, ең көп) адаптивті мәнді шекте ұстайды.");
Q("style","A2","What does width: min(100% - 40px, 1100px) aim to do?","width: min(100% - 40px, 1100px) не мақсатта қолданылады?",["Keep a 40px total side allowance and cap width at 1100px|Екі жаққа жалпы 40px орын қалдырып, енді 1100px-пен шектеу","Always make width 40px|Енді әрқашан 40px ету","Force width above 1100px|Енді 1100px-тен үлкен ету","Set height to 1100px|Биіктікті 1100px ету"],0,"min chooses the smaller calculated width, so the container fits narrower screens.","min екі еннің кішісін таңдайды, сондықтан контейнер тар экранға да сыяды.");
Q("effects","A3","What does inset: 0 do on an absolutely positioned overlay?","Absolute қабатқа inset: 0 не істейді?",["Sets top, right, bottom and left offsets to zero|Жоғары, оң, төмен және сол ығысуды нөл етеді","Sets opacity to zero|Мөлдірлікті нөл етеді","Creates a grid gap|Grid аралығын жасайды","Sets font size to zero|Қаріп өлшемін нөл етеді"],0,"It stretches the positioned overlay to all four edges of its containing block.","Ол position берілген қабатты контейнердің төрт шетіне дейін созады.");
Q("effects","A3","What does a linear-gradient background create?","linear-gradient фоны не жасайды?",["A smooth transition between colors|Түстердің біртіндеп ауысуын","A new HTML element|Жаңа HTML элементін","A table row|Кесте жолын","A fixed image size|Суреттің тұрақты өлшемін"],0,"Gradients can darken a hero image so overlaid text stays readable.","Градиент hero суретін қараңғылау етіп, үстіндегі мәтінді оқуға жеңілдетеді.");
Q("effects","A3","What does object-position: center 57% change with object-fit: cover?","object-fit: cover кезінде object-position: center 57% нені өзгертеді?",["Which part of the cropped image stays visible|Қиылған суреттің қай бөлігі көрінетінін","The image file path|Сурет файлының жолын","The image's alt text|Суреттің alt мәтінін","The card border radius|Карточка бұрышының радиусын"],0,"object-position moves the image inside its display box when cropping occurs.","object-position сурет қиылғанда оның қорап ішіндегі көрінетін орнын басқарады.");
Q("grid","A2","What does grid-auto-rows: 220px set?","grid-auto-rows: 220px нені белгілейді?",["Height of automatically created grid rows|Автоматты жасалған Grid жолдарының биіктігін","Width of every image|Әр суреттің енін","Gap between all columns|Барлық баған аралығын","The row's font size|Жолдың қаріп өлшемін"],0,"Implicit rows created beyond the template use the specified 220px size.","Үлгіден тыс автоматты пайда болған жолдар 220px биіктікті қолданады.");
Q("responsive","W3","Which Grid pattern can create responsive columns without a fixed number?","Баған санын алдын ала бекітпей адаптивті Grid жасайтын тәсіл қайсы?",["repeat(auto-fit, minmax(200px, 1fr))|repeat(auto-fit, minmax(200px, 1fr))","float: both|float: both","position: fixed|position: fixed","text-align: justify|text-align: justify"],0,"auto-fit fills the row with as many minimum-width tracks as can fit.","auto-fit жолға ең аз ені берілген бағандардың сыйғанынша орналастырады.");
